create table if not exists users
(
    id    bigint generated by default as identity,
    name  varchar(255),
    email varchar(50) not null,
    constraint users_pk
        primary key (id)
);

alter table users
    owner to root;

create unique index if not exists users_email_uindex
    on users (email);

